#!/bin/bash

if [ $# = 0 ] ; then
	curl http://ip-api.com/json/?fields=country,regioName,city,isp,org,reverse,mobile,proxy 2> /dev/null | jq
else
	while [ $# -gt 0 ]
	do
		curl http://ip-api.com/json/$1?fields=country,regioName,city,isp,org,reverse,mobile,proxy,query 2> /dev/null | jq
		shift
	done

fi




